[package]
name = "iron"
version = "0.1.0"
authors = ["iformas <iformas@hotmail.com>"]

[dependencies]
iron ="0.6.0"
hyper="0.12.14"
mount="0.4.0"
router="0.6.0"
staticfile="0.5.0"
handlebars = "1.1.0"
handlebars-iron="0.27.0"